### ISSUE TITLE
Open Project doesn't exist in scide in Linux

### ISSUE THREAD

**Issue by gilfuser** [miguel-negrao/scStandalone#3]
Hi
I'm trying to make a scStandalone in Linux, using SC 3.9dev.
I'm following the Read-me, but it seams like there's no Open > Project option in the IDE.

bests,
Gil

**Comment by miguel-negrao** [comment]
This approach to standalones only works when compiling SC with the patch I created for the "projects" feature ( https://github.com/supercollider/supercollider/pull/1978 ). Unfortunately at the moment the patch doesn't apply cleanly to master, I'm working on that. I will add a note about this to the readme.
